/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.neu.csye6200.daycare.view;

import edu.neu.csye6200.daycare.model.Person;
import edu.neu.csye6200.daycare.model.Student;
import edu.neu.csye6200.daycare.model.Teacher;
import edu.neu.csye6200.daycare.repositories.StudentRepository;
import edu.neu.csye6200.daycare.repositories.TeacherRepository;
import edu.neu.csye6200.daycare.utils.Utils;

import javax.swing.*;
import java.sql.SQLException;

import static edu.neu.csye6200.daycare.cronservice.LoginController.login;

/**
 *
 * @author dhairya
 */
public class LoginPageLayout extends javax.swing.JFrame {

    private TeacherRepository teacherRepository;
    private StudentRepository studentRepository;

    /**
     * Creates new form LoginPageLayout
     */
    public LoginPageLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Email ID");

        jLabel2.setText("Password");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt)  {
                try {
                    jButton1ActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!Utils.VALIDATE_EMAIL_ADDRESS.apply(jTextField1.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Enter a valid Email-Id", "Error!!",
                    JOptionPane.ERROR_MESSAGE);
            jTextField1.requestFocus();
            return;
        }
        if (jTextField2.getText().isEmpty() || jTextField2.getText().length() < 6) {
            JOptionPane.showMessageDialog(new JFrame(), "Password should be atleast 6 characters", "Error!!",
                    JOptionPane.ERROR_MESSAGE);
            jTextField2.requestFocus();
            return;
        }

        String Email = jTextField1.getText();
        String Password = jTextField2.getText();

        login(Email, Password);


//        Person currentPerson = null;
//        currentPerson = teacherRepository.getByEmailIdAndPassword(jTextField1.getText(), jTextField2.getText());
//        if (currentPerson != null) {
//            JOptionPane.showMessageDialog(new JFrame(), "Login Success as Teacher", "Login Success!!",
//                    JOptionPane.ERROR_MESSAGE);
//            dispose();
//            // Open the second frame
//            TeacherDashboardLayout secondFrame = new TeacherDashboardLayout((Teacher) currentPerson);
//            secondFrame.setVisible(true);
//        }
//        if (currentPerson == null) {
//            currentPerson = studentRepository.getByEmailIdAndPassword(jTextField1.getText(), jTextField2.getText());
//        }
//        if (currentPerson != null) {
//            System.out.println("Login Success as Parent");
//            JOptionPane.showMessageDialog(new JFrame(), "Login Success as Parent", "Login Success!!",
//                    JOptionPane.ERROR_MESSAGE);
//            dispose();
//            // Open the second frame
//            assert currentPerson instanceof Student;
//            StudentDashboardLayout secondFrame = new StudentDashboardLayout((Student) currentPerson);
//            secondFrame.setVisible(true);
//        }
//        if (currentPerson == null) {
//            System.out.println("Login Failed");
//            JOptionPane.showMessageDialog(new JFrame(), "Invalid UserName/Password", "Error!!",
//                    JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        
        // Open the second frame
        LandingPageLayout secondFrame = new LandingPageLayout();
        secondFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
